### ISSUE TITLE
Recurring Tasks icon (🔁) in the Tasks plugin

### ISSUE THREAD

**Issue by pppaapp** [andrewbrereton/obsidian-to-ical-plugin#11]
hello

The 🔁 is an icon used by the Tasks plugin
[https://publish.obsidian.md/tasks/Getting+Started/Recurring+Tasks](https://publish.obsidian.md/tasks/Getting+Started/Recurring+Tasks)

It would be better if the information associated with this icon was not visible on the calendar

![CleanShot 2023-11-09 at 23 00 56@2x](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/10ec0a08-2022-4280-bf88-b69348db92f5)

![CleanShot 2023-11-09 at 22 53 20@2x](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/91e7b96c-0fab-4068-af22-3ad54002986d)

**Comment by andrewbrereton** [comment]
Hi @pppaapp. This is fixed in [1.4.0](https://github.com/andrewbrereton/obsidian-to-ical-plugin/releases/tag/1.4.0). Thanks again
