### ISSUE TITLE
There is a url encoded issue with the string being written to .ics LOCATION

### ISSUE THREAD

**Issue by pppaapp** [andrewbrereton/obsidian-to-ical-plugin#17]
hello

![CleanShot 2023-11-30 at 12 05 38@2x](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/92206317-e050-45a8-a1f9-d78fc94f3b11)

`obsidian://open?vault=OBvault&file=Inbox/TEST 01.md.md`
this url does not work

`obsidian://open?vault=OBvault&file=Inbox%2FTEST%2001.md.md`
i modified it like above and it worked

**Comment by andrewbrereton** [comment]
Fixed in [1.7.1](https://github.com/andrewbrereton/obsidian-to-ical-plugin/releases/tag/1.7.1).

Thanks for your reports, I appreciate them.
