### ISSUE TITLE
does not generate events

### ISSUE THREAD

**Issue by pppaapp** [andrewbrereton/obsidian-to-ical-plugin#2]
Is the plugin not available yet?

![CleanShot 2023-10-30 at 10 29 58@2x](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/06a067ec-9b2e-4885-af87-38b2c1e90981)

**Comment by pppaapp** [comment]
Thank you

I reactivated the plugin and it worked

![CleanShot 2023-10-30 at 12 03 42@2x](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/a4ee34de-101f-48f6-a49c-644c172501b4)

📅 🛫 
Is there a feature that can handle this emoji?

This emoji is used by the tasks plugin
https://github.com/obsidian-tasks-group/obsidian-tasks

**Comment by andrewbrereton** [comment]
Oh, this is very interesting. I had not seen this plugin before. I've had a quick look at the [Obsidian Tasks Dates docs](https://publish.obsidian.md/tasks/Getting+Started/Dates) and I will be able to support Due Date, Scheduled Date, and Start Date easily.

However, things like this might be complicated to convert into an iCal `RRULE`:

```markdown
- [ ] Send Kate a birthday card - with a scheduled date 🔁 every January on the 4th ⏳ 2023-01-04
```

I'll add this to the todo list.

**Comment by andrewbrereton** [comment]
For the example that you provided:

```markdown
- [ ] banana 🛫 2023-10-30 📅 2023-10-31
```

What would you expect to see in your calendar?

I assume two calendar events like this:

<img width="499" alt="image" src="https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/682893/01157429-02ca-4898-9545-c01c14a3da22">

**Comment by pppaapp** [comment]
Wouldn't it be nice to see it as one event?

![CleanShot 2023-10-30 at 19 10 37@2x](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/921dfdac-973e-41f2-96c7-f25924f13e01)

**Comment by andrewbrereton** [comment]
Sure thing. That is why I asked. I will implement this when I can.

**Comment by andrewbrereton** [comment]
Hi @pppaapp

Support for Obsidian Tasks in emoji format has been done. Please use the latest release (https://github.com/andrewbrereton/obsidian-to-ical-plugin/releases/tag/1.3.0).

I'm closing this issue it has been resolved. If there are further problems, please create a new issue. Thanks.
