### ISSUE TITLE
Instructions are unclear 

### ISSUE THREAD

**Issue by Gourav1910** [andrewbrereton/obsidian-to-ical-plugin#22]
As a non coder I tried to connect gist with iCal plugin so that I can connect it with google calendar but it is not working. As I am also unfamiliar with github so is there any clear instruction which I could follow? It would be helpful. 

So far I created a personal access token but I don't know whether I created it right or wrong. It was asking so many permission but I allowed the gist permission. I connected a random repository to it. Then I created the token and put its code in ical plugin.

Then I created a gist by watching a youtube video. I created a random readme .md file so that it allow me to create a gist but after that I don't know where to find its ID to put it in plugin.

And also I don't see any option to connect it with google calendar. That's why I got confused and opened this issue. Could you please help me🙏.

**Comment by andrewbrereton** [comment]
Hi @Gourav1910, thanks for the interest. I'll describe the steps. I will make a note to update the README so it is more clear. I will also consider adding the ability to save the calendar to other storage options if that is desired.

## Personal access token

It sounds like you did this correctly. You are correct, it only needs the `gist` permission. The token should start in `ghp_` followed by a lot of random letters and numbers.

## Gist

1. Go to here to create a new Gist: https://gist.github.com/
1.1 `Gist description`: Enter anything you like. Eg: My calendar that is generated from my Obsidian vault 
1.2 Filename including extension: `obsidian.ics`
1.3 For the contents of the Gist, just put anything in there. The iCal plugin will overwrite it.
1.4 Click `Create secret gist`

After you create the Gist, you will see the URL is something like:

```
https://gist.github.com/andrewbrereton/11c399ce6c0d89c5f8101edb9a2b76d6`

                        |------------| |------------------------------|
                           Username                 Gist ID
```

## Configure iCal

You now have all the information. In Obsidian, open your settings, and go down to the `iCal` plugin.

1. Ensure `Save calendar to GitHub Gist?` is enabled.
2. `GitHub personal access token` should be that one that starts in `ghp_` followed by a bunch of random letters and numbers.
3. `GitHub Gist ID`: This is in the URL of the Gist you just created.
4. `GitHub username`: This is in the URL of the Gist you just created.
5. `Filename`: obsidian.ics (Should match the name you gave in step 1.2).

## Configure Google Calendar

Once the Gist settings are working, the plugin settings screen will show you the URL where the calendar will be available. Click the `📋 Copy to clipboard` button.

1. Go to: https://calendar.google.com
2. Click the ➕ button to add another calendar
3. Click `From URL`
4. Paste the URL that you copied to your clipboard
5. Click `Add calendar`

That's it.

Please note: Your calendar will be generated every 5 minutes (by default). There may also be a delay from Google fetching the latest calendar. So sometimes it could take up to 10 minutes for events to reflect on your calendar.

Please let me know how you go.

**Comment by Gourav1910** [comment]
> Hi @Gourav1910, thanks for the interest. I'll describe the steps. I will make a note to update the README so it is more clear. I will also consider adding the ability to save the calendar to other storage options if that is desired.
> 
> ## Personal access token
> It sounds like you did this correctly. You are correct, it only needs the `gist` permission. The token should start in `ghp_` followed by a lot of random letters and numbers.
> 
> ## Gist
> 1. Go to here to create a new Gist: https://gist.github.com/
>    1.1 `Gist description`: Enter anything you like. Eg: My calendar that is generated from my Obsidian vault
>    1.2 Filename including extension: `obsidian.ics`
>    1.3 For the contents of the Gist, just put anything in there. The iCal plugin will overwrite it.
>    1.4 Click `Create secret gist`
> 
> After you create the Gist, you will see the URL is something like:
> 
> ```
> https://gist.github.com/andrewbrereton/11c399ce6c0d89c5f8101edb9a2b76d6
> 
>                         |------------| |------------------------------|
>                            Username                 Gist ID
> ```
> 
> ## Configure iCal
> You now have all the information. In Obsidian, open your settings, and go down to the `iCal` plugin.
> 
> 1. Ensure `Save calendar to GitHub Gist?` is enabled.
> 2. `GitHub personal access token` should be that one that starts in `ghp_` followed by a bunch of random letters and numbers.
> 3. `GitHub Gist ID`: This is in the URL of the Gist you just created.
> 4. `GitHub username`: This is in the URL of the Gist you just created.
> 5. `Filename`: obsidian.ics (Should match the name you gave in step 1.2).
> 
> ## Configure Google Calendar
> Once the Gist settings are working, the plugin settings screen will show you the URL where the calendar will be available. Click the `📋 Copy to clipboard` button.
> 
> 1. Go to: https://calendar.google.com
> 2. Click the ➕ button to add another calendar
> 3. Click `From URL`
> 4. Paste the URL that you copied to your clipboard
> 5. Click `Add calendar`
> 
> That's it.
> 
> Please note: Your calendar will be generated every 5 minutes (by default). There may also be a delay from Google fetching the latest calendar. So sometimes it could take up to 10 minutes for events to reflect on your calendar.
> 
> Please let me know how you go.

OMG thankyou so much. You just gave me the most easiest tutorial that I could follow. You are doing good work here by genuinely helping people🥰. Ok I will let you know after implementing all the steps. 

Just for the context, my ideas was whatever task that i will create in obsidian by using task plugin and which also has a date should be automatically shown in my google calendar(10min update delay is ok for me). So that I won't miss my obsidian related task and also I don't have to open my obsidian just to look for tasks that I got to do at any particular date.

**Comment by andrewbrereton** [comment]
I'm going to close this issue as I've updated the [README](https://github.com/andrewbrereton/obsidian-to-ical-plugin#readme) to include this information. Thanks again.
