### ISSUE TITLE
I need an option to not generate completed tasks as ical

### ISSUE THREAD

**Issue by ssifuu** [andrewbrereton/obsidian-to-ical-plugin#25]

**Comment by andrewbrereton** [comment]
This has been fixed in [1.9.0](https://github.com/andrewbrereton/obsidian-to-ical-plugin/releases/tag/1.9.0).

There is a new setting in the iCal settings page where you can optionally ignore completed tasks.

**Comment by jlbnetwork** [comment]
Hello.

I'm running Obsidian to iCal 2.0.1 in Obsidian 1.8.10.

I set everything up correctly using a secret Github Gist and I subscribed to the URL and Google Calendar shows me all the tasks as events, like it's set up.

However, even with "Ignore completed tasks" selected, when an event is already created and I later on, mark it as completed, it doesn't get removed from the calendar.

When I inspect the gist, the completed task is not there anymore, however, it's still showing up in Google Calendar more than 4 hours later.
