### ISSUE TITLE
[question] Scheduled VS Deadline in GTD workflow

### ISSUE THREAD

**Issue by bepolymathe** [andrewbrereton/obsidian-to-ical-plugin#30]
Hi @andrewbrereton 

As I understand how the plugin works, this one follows the following logic: 
1. if there's only one planning date, it's also used as a due date... and therefore appears in the export calendar on that date. 
2. if there is only a due date, it is exported as a due date. 
3. if there is both a planning date and a due date, the due date is given priority in the agenda (even if both exist in the file). 

This behavior is quite logical in a pure planning strategy, but poses a bit of a problem in a GTD logic. In GTD, it's the planning dates that are important (when I decide to do it) and the due dates, when they exist, are indicative. Not every task has a hard deadline. 

I'd like to find a solution to this problem. Would you be interested?

One solution might be to export tasks with only a deadline with an emoji 📅 and tasks with only a schedule with an emoji ⌛ (this follows the plugin in obsidian). For tasks with both, the task would be duplicated with a first task including 📅 and a second including ⌛

**Comment by andrewbrereton** [comment]
Hi @bepolymathe

Your understanding of the logic is correct.

I think I might add a setting to support this use case. Something like:

`What do you want to do with tasks that have a due date and a start date?`

Options:

1. Prefer due date
2. Prefer start date
3. Create an event for each date

Option 1 is the current behaviour. 

How does that sound?

**Comment by andrewbrereton** [comment]
Hi @bepolymathe 

I've created a Pull Request that I think solves your issue.

https://github.com/andrewbrereton/obsidian-to-ical-plugin/pull/47

I've described the logic in the description. Please review and let me know if this solves this issue or not. I'm happy to receive feedback, rewrite things, tweak things, etc.

**Comment by andrewbrereton** [comment]
Hi @bepolymathe

This has been done in [1.13.0](https://github.com/andrewbrereton/obsidian-to-ical-plugin/releases/tag/1.13.0). Please update your plugin and let me know how it goes.

Thanks for your suggestion.

**Comment by andrewbrereton** [comment]
I'm really happy to hear that! You're very welcome. If there are any issues or other feature requests, feel free to ask.
