### ISSUE TITLE
(idea) support task list filtering based on tags

### ISSUE THREAD

**Issue by oblique01** [andrewbrereton/obsidian-to-ical-plugin#69]
I often have lots of tasks in a day but only need to calendar schedule a few of them that are really important. It'd be helpful if (say) a tag could be used to filter in (or out) tasks that go into the ics file.

[Nice work by the way. I found this only recently and will pull this into my workflow. At a quick test, it looks like the ics file can also be used with BusyCal on Mac]

**Comment by andrewbrereton** [comment]
This is a good feature. I'll create a setting to which allows you to enter one (or more?) tags that you want to exclude from your iCalendar file. So you could set it to ignore tasks that contain `#ignore`, or `#no-calendar`, or `#secret`, or `#pii`, etc.

An alternative could be to only include tasks that have certain tags.

Or I could add both to the settings I suppose.

Let me know your thoughts.

**Comment by andrewbrereton** [comment]
![image](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/682893/1e9d9145-6b32-4f1d-a96b-86723f944a30)

**Comment by andrewbrereton** [comment]
Hi @oblique01

This has been done in release [1.19.0](https://github.com/andrewbrereton/obsidian-to-ical-plugin/releases/tag/1.19.0). Please update the plugin in Obsidian to see the changes.

Let me know if there are further issues.

**Comment by oblique01** [comment]
Thanks lots and sorry for delayed reply, been ill.  Looking at the notes quickly, looks like you implemented both inclusion and exclusion, which is probably worthwhile having both.  This will really help hugely in not 'swamping' a calendar import with tasks that don't need to be scheduled. I'll lookin forward to using this when I'm back up to speed. Many thanks.

**Comment by andrewbrereton** [comment]
You're welcome. I hope you have a speedy recovery!
