### ISSUE TITLE
DTSTART,DTEND empty

### ISSUE THREAD

**Issue by pppaapp** [andrewbrereton/obsidian-to-ical-plugin#7]
I created a task that doesn't include 🛫 in the task

<img width="491" alt="CleanShot 2023-11-07 at 13 02 58@2x" src="https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/4c41197a-1f00-4f48-b577-f98b39173b10">

In this case, DTSTART and DTEND will not be generated

<img width="535" alt="CleanShot 2023-11-07 at 13 03 04@2x" src="https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/c3669d63-7132-4c03-ac30-9fa68a64a5fb">

![CleanShot 2023-11-07 at 13 03 21@2x](https://github.com/andrewbrereton/obsidian-to-ical-plugin/assets/31263588/1248fa32-6566-4275-b90e-317092add7e8)

**Comment by andrewbrereton** [comment]
Thank you @pppaapp.

This has been fixed in release [1.3.1](https://github.com/andrewbrereton/obsidian-to-ical-plugin/releases/tag/1.3.1).
